# temporary directory. some intermediate data is stored to this directory
dirtemp = '/scratch/gito_aciar/tmp'
# plot directory.
dirplot = '/scratch/gito_aciar/tmp/plot-precip'
# map output directory.
dirpmap = '/scratch/gito_aciar/tmp/map-precip'
# chirps monthly data (netcdf format)
dataref = '/scratch/gito_aciar/sdm-toolbox/out/leptocybe-invasa/input/train/tmp/chrips_bias.nc'
# cmip monthly historical data (netcdf format)
datahis = '/scratch/gito_aciar/sdm-toolbox/out/leptocybe-invasa/input/train/tmp/pr_histo_bias.nc'
# cmip monthly future data (netcdf format)
datafut = '/scratch/gito_aciar/sdm-toolbox/out/leptocybe-invasa/input/train/tmp/pr_future_bias.nc'
# output of corrected cmip monthly historical data (netcdf format)
dhiscor = '/scratch/gito_aciar/sdm-toolbox/out/leptocybe-invasa/input/train/tmp/pr_histo-corr.nc'
# output of corrected cmip monthly future data (netcdf format)
dfutcor = '/scratch/gito_aciar/sdm-toolbox/out/leptocybe-invasa/input/train/tmp/pr_future-corr.nc'
# function to adjust cmip data unit
funcadj = '-mulc,86400'
# chirps variable nama
drefvar = 'precip'
# cmip variable name (historical data)
dhisvar = 'pr'
# cmip variable name (future data)
dfutvar = 'pr'
# cmip variable unit
varunit = 'mm'
# label/name data ref to place on plot
drefname = 'CHIRPS'
# label/name data cor to place on plot
dcorname = 'C6-BCC-CSM2'
# correction method [gamma|normal]
crmethod = 'gamma'
# bounding box [lon0, lon1, lat0, lat1]
#bbox = [100, 115, -4, 2]
